name: Comment on the pull request

on:
  workflow_run:
    # match the name of the other workflow here:
    workflows: ["CI"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Coveage Comment
        uses: mutility/coverpkg@forked-pr
        with:
          comment: replace
          from-artifacts: true
